// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("products")]
public partial class Product
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("categoryID")]
    public int? CategoryId { get; set; }

    [Column("name")]
    [StringLength(50)]
    //[Unicode(false)]
    public string Name { get; set; }

    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Column("imageUrl")]
    [StringLength(50)]
    //[Unicode(false)]
    public string ImageUrl { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}